disabled_rules: # rule identifiers to exclude from running
  - function_parameter_count
  - trailing_whitespace
  - colon
opt_in_rules: # some rules are only opt-in
  - empty_count 
  - force_unwrapping
  - explicit_acl
  - explicit_top_level_acl
  - missing_docs
  - comma
  - control_statement
  - fatal_error_message
  - unneeded_break_in_switch
  - unused_optional_binding
  - array_init
  - empty_parentheses_with_trailing_closure
  - block_based_kvo
  - class_delegate_protocol
  - first_where
  - for_where
  - shorthand_operator
  - no_extension_access_modifier
  - syntactic_sugar
  - weak_delegate
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  excluded:
    - id
    - on
    - off
    - ID
    - URL
    - GlobalAPIKey
  min_length:
    warning: 2
    error: 1
  max_length: 40
  
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)